import type { NextPage } from "next";
import Head from "next/head";
import { useAuth } from "../components/hooks/useAuth";
import { Container } from "../components/layouts/Container";
import { Header } from "../components/layouts/Header";
import Login from "../components/user/Login";
import Register from "../components/user/Register";
import { startGoogleSignIn } from "../store/auth";
import { useAppDispatch, useAppSelector } from "../hooks";
import { useMemo } from "react";

const Home: NextPage = () => {
  const { status } = useAppSelector((state) => state.auth);

  const dispatch = useAppDispatch();

  const isAuthenticating = useMemo(() => status === "checking", [status]);

  const onGoogleSignIn = () => {
    dispatch(startGoogleSignIn());
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <main>
          <h1 className="text-3xl font-bold my-5">Cards</h1>
          <p>
            Aplicación para crearse colecciones de tarjetas para aprender
            vocabulario en inglés.
          </p>
          <p>
            A partir de las tarjetas se pueden hacer ejercicios en donde el
            usuario completa y va progresando para aprender nuevas palabras.
          </p>
          <p>Se puede reproducir el contenido de la tarjeta</p>
          <p>
            Se pueden guardar colecciones enteras o tarjetas particulares
            existentes en la app a alguna coleccion del usuario.{" "}
          </p>
          <br />
          <h2>Registrar usuario</h2>
          <Register />
          <hr />
          <h2>Login</h2>
          <Login />
          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
            onClick={onGoogleSignIn}
            disabled={isAuthenticating}
          >
            Login with Google
          </button>
        </main>
      </Container>
    </div>
  );
};

export default Home;
